apiVersion: v1
kind: Secret
metadata:
  name: resysched-secret
  namespace: resysched
type: Opaque
stringData:
  DATABASE_URL: "postgres://resy:resy@postgres.resysched.svc.cluster.local:5432/resy?sslmode=disable"
  COOKIE_HASH_KEY: "BASE64_HERE"
  COOKIE_BLOCK_KEY: "BASE64_HERE"
